package com.mcf.davidee.guilib;

import java.util.Arrays;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = "guilib", name = "GUI Library", version = "Mau_1.0.1")
public class GuiLibrary {

	
	@EventHandler 
	public void preInit(FMLPreInitializationEvent event) {
		ModMetadata modMeta = event.getModMetadata();
		modMeta.authorList = Arrays.asList("Davidee", "Tulir293");
		modMeta.autogenerated = false;
		modMeta.credits = "Thanks to Mojang, Forge, and all your support. Updated to 1.8 by Tulir293";
		modMeta.description = "A small library for creating minecraft GUIs.";
		modMeta.url = "http://www.minecraftforum.net/topic/1909236-/";
	}
	
}
